# https://github.com/angular-eslint/angular-eslint#readme
root: true
ignorePatterns:
- projects/**/*
- node_modules/

overrides:
# -----------------------------------------------------
# TYPESCRIPT FILES (COMPONENTS, SERVICES ETC) (.ts)
# -----------------------------------------------------
- files:
  - "*.ts"
  parserOptions:
    project:
    - tsconfig.json
    createDefaultProgram: true
  extends:
  - plugin:@angular-eslint/recommended
  - plugin:@angular-eslint/template/process-inline-templates
  rules:
    "@angular-eslint/directive-selector":
    - error
    - type: attribute
      prefix: app
      style: camelCase
    "@angular-eslint/component-selector":
    - error
    - type: element
      prefix: app
      style: kebab-case
    no-unused-vars: 1
# -----------------------------------------------------
# COMPONENT TEMPLATES
# -----------------------------------------------------
- files:
  - "*.html"
  extends:
  - plugin:@angular-eslint/template/recommended
  - plugin:prettier/recommended
  plugins:
    - "html"
  rules:
    prettier/prettier:
    - error
    - parser: angular
  parser: angular